version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-orchestrator-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./modules:/app/modules  # 模块热加载目录

volumes:
  redis-data: